In [38]:
%matplotlib notebook
from matplotlib import pyplot as plt
from scipy import stats
import numpy as np
import pandas as pd
import pprint as pprint

In [39]:
file=r'\Users\n8gre\crimes_-_2001_to_present.csv'
df=pd.read_csv(file)

In [55]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10000092,HY189866,03/18/2015 07:44:00 PM,047XX W OHIO ST,041A,BATTERY,AGGRAVATED: HANDGUN,STREET,False,False,...,28.0,25.0,04B,1144606.0,1903566.0,2015,02/10/2018 03:50:01 PM,41.891399,-87.744385,"(41.891398861, -87.744384567)"
1,10000094,HY190059,03/18/2015 11:00:00 PM,066XX S MARSHFIELD AVE,4625,OTHER OFFENSE,PAROLE VIOLATION,STREET,True,False,...,15.0,67.0,26,1166468.0,1860715.0,2015,02/10/2018 03:50:01 PM,41.773372,-87.665319,"(41.773371528, -87.665319468)"
2,10000095,HY190052,03/18/2015 10:45:00 PM,044XX S LAKE PARK AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,4.0,39.0,08B,1185075.0,1875622.0,2015,02/10/2018 03:50:01 PM,41.813861,-87.596643,"(41.81386068, -87.596642837)"
3,10000096,HY190054,03/18/2015 10:30:00 PM,051XX S MICHIGAN AVE,0460,BATTERY,SIMPLE,APARTMENT,False,False,...,3.0,40.0,08B,1178033.0,1870804.0,2015,02/10/2018 03:50:01 PM,41.800802,-87.622619,"(41.800802415, -87.622619343)"
4,10000097,HY189976,03/18/2015 09:00:00 PM,047XX W ADAMS ST,031A,ROBBERY,ARMED: HANDGUN,SIDEWALK,False,False,...,28.0,25.0,03,1144920.0,1898709.0,2015,02/10/2018 03:50:01 PM,41.878065,-87.743354,"(41.878064761, -87.743354013)"

In [90]:
df2 = df.loc[:, ["Year", "Location Description", "ID"]]
df3=df2.loc[(df2["Year"]>2011)]
df4=df3.loc[(df3["Year"]<2016)]

In [59]:
#df.pivot(index='ID', columns='Year', values='Location Description')

In [91]:
loc=df4.groupby(["Location Description", "Year"])["ID"].count()
loc

Location Description                                   Year
ABANDONED BUILDING                                     2012    1036
                                                       2013     977
                                                       2014     680
                                                       2015     526
AIRCRAFT                                               2012      46
                                                       2013      61
                                                       2014      74
                                                       2015     107
AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA        2012     102
                                                       2013      67
                                                       2014      73
                                                       2015      78
AIRPORT BUILDING NON-TERMINAL - SECURE AREA            2012      54
                                                       2013      59
                                                       2014      50
                                                       2015      68
AIRPORT EXTERIOR - NON-SECURE AREA                     2012      92
                                                       2013      41
                                                       2014      60
                                                       2015      60
AIRPORT EXTERIOR - SECURE AREA                         2012      26
                                                       2013      37
                                                       2014      26
                                                       2015      44
AIRPORT PARKING LOT                                    2012      65
                                                       2013      76
                                                       2014      64
                                                       2015      86
AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA         2012     149
                                                       2013     122
                                                               ...
VACANT LOT                                             2014       3
VACANT LOT/LAND                                        2012    1623
                                                       2013    1673
                                                       2014    1300
                                                       2015    1126
VEHICLE - DELIVERY TRUCK                               2014       2
                                                       2015      21
VEHICLE - OTHER RIDE SERVICE                           2012       1
                                                       2015      64
VEHICLE - OTHER RIDE SHARE SERVICE (E.G., UBER, LYFT)  2014       1
                                                       2015       1
VEHICLE NON-COMMERCIAL                                 2012    5490
                                                       2013    5329
                                                       2014    4839
                                                       2015    4686
VEHICLE-COMMERCIAL                                     2012     294
                                                       2013     263
                                                       2014     252
                                                       2015     242
VESTIBULE                                              2012       1
                                                       2013       3
                                                       2014       1
WAREHOUSE                                              2012     404
                                                       2013     332
                                                       2014     273
                                                       2015     248
YARD                                                   2012      11
                                                       2013      18
                                                       2014      11
                                                       2015      14
Name: ID, Length: 476, dtype: int64

In [74]:
loc.apply.count("Year")

AttributeError: 'function' object has no attribute 'count'